# Generated by Django 4.2.1 on 2023-06-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
