# Generated by Django 4.2.1 on 2023-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_postcode_checkout_phonenumber_checkout_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
