# Generated by Django 4.2.1 on 2023-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_first', models.CharField(max_length=100)),
                ('title_second', models.CharField(max_length=100)),
                ('image1', models.CharField(max_length=200)),
                ('image2', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_first', models.CharField(max_length=100)),
                ('title_second', models.CharField(max_length=100)),
                ('content_first', models.CharField(max_length=200)),
                ('content_second', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
