# Generated by Django 4.2.1 on 2023-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image1',
            field=models.ImageField(upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image2',
            field=models.ImageField(upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(upload_to='intro_images/'),
        ),
    ]
