# Generated by Django 4.2.1 on 2023-06-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price2',
        ),
    ]
