# Generated by Django 4.2.1 on 2023-07-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_image_remove_orderitem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
