# Generated by Django 4.2.1 on 2023-07-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order'),
        ),
    ]
