# Generated by Django 4.2.1 on 2023-07-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_orderitem_product_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(default='session-id', max_length=40),
        ),
    ]
