# Generated by Django 4.2.1 on 2023-07-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
    ]
