# Generated by Django 4.2.1 on 2023-07-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_payment_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_done',
        ),
    ]
